//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  settings: Settings;
  settingsConnection: SettingsConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
  restaurants: Restaurants;
  restaurantsConnection: RestaurantsConnection;
  laundry: Laundry;
  laundryConnection: LaundryConnection;
  transport: Transport;
  transportConnection: TransportConnection;
  bars: Bars;
  barsConnection: BarsConnection;
  activities: Activities;
  activitiesConnection: ActivitiesConnection;
  amenities: Amenities;
  amenitiesConnection: AmenitiesConnection;
  events: Events;
  eventsConnection: EventsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryRestaurantsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRestaurantsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RestaurantsFilter>;
};


export type QueryLaundryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLaundryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LaundryFilter>;
};


export type QueryTransportArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTransportConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TransportFilter>;
};


export type QueryBarsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBarsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BarsFilter>;
};


export type QueryActivitiesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryActivitiesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActivitiesFilter>;
};


export type QueryAmenitiesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAmenitiesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AmenitiesFilter>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};

export type DocumentFilter = {
  settings?: InputMaybe<SettingsFilter>;
  pages?: InputMaybe<PagesFilter>;
  restaurants?: InputMaybe<RestaurantsFilter>;
  laundry?: InputMaybe<LaundryFilter>;
  transport?: InputMaybe<TransportFilter>;
  bars?: InputMaybe<BarsFilter>;
  activities?: InputMaybe<ActivitiesFilter>;
  amenities?: InputMaybe<AmenitiesFilter>;
  events?: InputMaybe<EventsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Settings | Pages | Restaurants | Laundry | Transport | Bars | Activities | Amenities | Events | Folder;

export type SettingsBranding = {
  __typename?: 'SettingsBranding';
  primaryColor?: Maybe<Scalars['String']['output']>;
  accentColor?: Maybe<Scalars['String']['output']>;
};

export type SettingsWifi = {
  __typename?: 'SettingsWifi';
  networkName: Scalars['String']['output'];
  password: Scalars['String']['output'];
};

export type SettingsCheckTimes = {
  __typename?: 'SettingsCheckTimes';
  checkIn?: Maybe<Scalars['String']['output']>;
  checkOut?: Maybe<Scalars['String']['output']>;
};

export type SettingsContacts = {
  __typename?: 'SettingsContacts';
  whatsapp?: Maybe<Scalars['String']['output']>;
  emergencyLocal?: Maybe<Scalars['String']['output']>;
  emergencyAmbulance?: Maybe<Scalars['String']['output']>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  hostelName: Scalars['String']['output'];
  logo?: Maybe<Scalars['String']['output']>;
  branding?: Maybe<SettingsBranding>;
  wifi?: Maybe<SettingsWifi>;
  checkTimes?: Maybe<SettingsCheckTimes>;
  contacts?: Maybe<SettingsContacts>;
  timezone?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsBrandingFilter = {
  primaryColor?: InputMaybe<StringFilter>;
  accentColor?: InputMaybe<StringFilter>;
};

export type SettingsWifiFilter = {
  networkName?: InputMaybe<StringFilter>;
  password?: InputMaybe<StringFilter>;
};

export type SettingsCheckTimesFilter = {
  checkIn?: InputMaybe<StringFilter>;
  checkOut?: InputMaybe<StringFilter>;
};

export type SettingsContactsFilter = {
  whatsapp?: InputMaybe<StringFilter>;
  emergencyLocal?: InputMaybe<StringFilter>;
  emergencyAmbulance?: InputMaybe<StringFilter>;
};

export type SettingsFilter = {
  hostelName?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  branding?: InputMaybe<SettingsBrandingFilter>;
  wifi?: InputMaybe<SettingsWifiFilter>;
  checkTimes?: InputMaybe<SettingsCheckTimesFilter>;
  contacts?: InputMaybe<SettingsContactsFilter>;
  timezone?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type RestaurantsSpotsCoordinates = {
  __typename?: 'RestaurantsSpotsCoordinates';
  lat?: Maybe<Scalars['Float']['output']>;
  lng?: Maybe<Scalars['Float']['output']>;
};

export type RestaurantsSpots = {
  __typename?: 'RestaurantsSpots';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  isHotelService?: Maybe<Scalars['Boolean']['output']>;
  linkedAmenityId?: Maybe<Scalars['String']['output']>;
  cuisineType?: Maybe<Scalars['String']['output']>;
  priceRange?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  coordinates?: Maybe<RestaurantsSpotsCoordinates>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Restaurants = Node & Document & {
  __typename?: 'Restaurants';
  spots?: Maybe<Array<Maybe<RestaurantsSpots>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RestaurantsSpotsCoordinatesFilter = {
  lat?: InputMaybe<NumberFilter>;
  lng?: InputMaybe<NumberFilter>;
};

export type RestaurantsSpotsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  isHotelService?: InputMaybe<BooleanFilter>;
  linkedAmenityId?: InputMaybe<StringFilter>;
  cuisineType?: InputMaybe<StringFilter>;
  priceRange?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  address?: InputMaybe<StringFilter>;
  coordinates?: InputMaybe<RestaurantsSpotsCoordinatesFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type RestaurantsFilter = {
  spots?: InputMaybe<RestaurantsSpotsFilter>;
};

export type RestaurantsConnectionEdges = {
  __typename?: 'RestaurantsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Restaurants>;
};

export type RestaurantsConnection = Connection & {
  __typename?: 'RestaurantsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RestaurantsConnectionEdges>>>;
};

export type LaundrySpotsCoordinates = {
  __typename?: 'LaundrySpotsCoordinates';
  lat?: Maybe<Scalars['Float']['output']>;
  lng?: Maybe<Scalars['Float']['output']>;
};

export type LaundrySpots = {
  __typename?: 'LaundrySpots';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  isHotelService?: Maybe<Scalars['Boolean']['output']>;
  linkedAmenityId?: Maybe<Scalars['String']['output']>;
  serviceType?: Maybe<Scalars['String']['output']>;
  priceRange?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  coordinates?: Maybe<LaundrySpotsCoordinates>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Laundry = Node & Document & {
  __typename?: 'Laundry';
  spots?: Maybe<Array<Maybe<LaundrySpots>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LaundrySpotsCoordinatesFilter = {
  lat?: InputMaybe<NumberFilter>;
  lng?: InputMaybe<NumberFilter>;
};

export type LaundrySpotsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  isHotelService?: InputMaybe<BooleanFilter>;
  linkedAmenityId?: InputMaybe<StringFilter>;
  serviceType?: InputMaybe<StringFilter>;
  priceRange?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  address?: InputMaybe<StringFilter>;
  coordinates?: InputMaybe<LaundrySpotsCoordinatesFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type LaundryFilter = {
  spots?: InputMaybe<LaundrySpotsFilter>;
};

export type LaundryConnectionEdges = {
  __typename?: 'LaundryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Laundry>;
};

export type LaundryConnection = Connection & {
  __typename?: 'LaundryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LaundryConnectionEdges>>>;
};

export type TransportSpotsCoordinates = {
  __typename?: 'TransportSpotsCoordinates';
  lat?: Maybe<Scalars['Float']['output']>;
  lng?: Maybe<Scalars['Float']['output']>;
};

export type TransportSpots = {
  __typename?: 'TransportSpots';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  isHotelService?: Maybe<Scalars['Boolean']['output']>;
  linkedAmenityId?: Maybe<Scalars['String']['output']>;
  transportType?: Maybe<Scalars['String']['output']>;
  priceRange?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  coordinates?: Maybe<TransportSpotsCoordinates>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Transport = Node & Document & {
  __typename?: 'Transport';
  spots?: Maybe<Array<Maybe<TransportSpots>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TransportSpotsCoordinatesFilter = {
  lat?: InputMaybe<NumberFilter>;
  lng?: InputMaybe<NumberFilter>;
};

export type TransportSpotsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  isHotelService?: InputMaybe<BooleanFilter>;
  linkedAmenityId?: InputMaybe<StringFilter>;
  transportType?: InputMaybe<StringFilter>;
  priceRange?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  address?: InputMaybe<StringFilter>;
  coordinates?: InputMaybe<TransportSpotsCoordinatesFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type TransportFilter = {
  spots?: InputMaybe<TransportSpotsFilter>;
};

export type TransportConnectionEdges = {
  __typename?: 'TransportConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Transport>;
};

export type TransportConnection = Connection & {
  __typename?: 'TransportConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TransportConnectionEdges>>>;
};

export type BarsSpotsCoordinates = {
  __typename?: 'BarsSpotsCoordinates';
  lat?: Maybe<Scalars['Float']['output']>;
  lng?: Maybe<Scalars['Float']['output']>;
};

export type BarsSpots = {
  __typename?: 'BarsSpots';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  isHotelService?: Maybe<Scalars['Boolean']['output']>;
  linkedAmenityId?: Maybe<Scalars['String']['output']>;
  barType?: Maybe<Scalars['String']['output']>;
  priceRange?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  coordinates?: Maybe<BarsSpotsCoordinates>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Bars = Node & Document & {
  __typename?: 'Bars';
  spots?: Maybe<Array<Maybe<BarsSpots>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BarsSpotsCoordinatesFilter = {
  lat?: InputMaybe<NumberFilter>;
  lng?: InputMaybe<NumberFilter>;
};

export type BarsSpotsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  isHotelService?: InputMaybe<BooleanFilter>;
  linkedAmenityId?: InputMaybe<StringFilter>;
  barType?: InputMaybe<StringFilter>;
  priceRange?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  address?: InputMaybe<StringFilter>;
  coordinates?: InputMaybe<BarsSpotsCoordinatesFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type BarsFilter = {
  spots?: InputMaybe<BarsSpotsFilter>;
};

export type BarsConnectionEdges = {
  __typename?: 'BarsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Bars>;
};

export type BarsConnection = Connection & {
  __typename?: 'BarsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BarsConnectionEdges>>>;
};

export type ActivitiesSpotsCoordinates = {
  __typename?: 'ActivitiesSpotsCoordinates';
  lat?: Maybe<Scalars['Float']['output']>;
  lng?: Maybe<Scalars['Float']['output']>;
};

export type ActivitiesSpots = {
  __typename?: 'ActivitiesSpots';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  isHotelService?: Maybe<Scalars['Boolean']['output']>;
  linkedAmenityId?: Maybe<Scalars['String']['output']>;
  activityType?: Maybe<Scalars['String']['output']>;
  priceRange?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  coordinates?: Maybe<ActivitiesSpotsCoordinates>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Activities = Node & Document & {
  __typename?: 'Activities';
  spots?: Maybe<Array<Maybe<ActivitiesSpots>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ActivitiesSpotsCoordinatesFilter = {
  lat?: InputMaybe<NumberFilter>;
  lng?: InputMaybe<NumberFilter>;
};

export type ActivitiesSpotsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  isHotelService?: InputMaybe<BooleanFilter>;
  linkedAmenityId?: InputMaybe<StringFilter>;
  activityType?: InputMaybe<StringFilter>;
  priceRange?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  address?: InputMaybe<StringFilter>;
  coordinates?: InputMaybe<ActivitiesSpotsCoordinatesFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type ActivitiesFilter = {
  spots?: InputMaybe<ActivitiesSpotsFilter>;
};

export type ActivitiesConnectionEdges = {
  __typename?: 'ActivitiesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Activities>;
};

export type ActivitiesConnection = Connection & {
  __typename?: 'ActivitiesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ActivitiesConnectionEdges>>>;
};

export type AmenitiesAmenities = {
  __typename?: 'AmenitiesAmenities';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  amenityType?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['JSON']['output']>;
  isHighlighted?: Maybe<Scalars['Boolean']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Amenities = Node & Document & {
  __typename?: 'Amenities';
  amenities?: Maybe<Array<Maybe<AmenitiesAmenities>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AmenitiesAmenitiesFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  amenityType?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  details?: InputMaybe<RichTextFilter>;
  isHighlighted?: InputMaybe<BooleanFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type AmenitiesFilter = {
  amenities?: InputMaybe<AmenitiesAmenitiesFilter>;
};

export type AmenitiesConnectionEdges = {
  __typename?: 'AmenitiesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Amenities>;
};

export type AmenitiesConnection = Connection & {
  __typename?: 'AmenitiesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AmenitiesConnectionEdges>>>;
};

export type EventsEventsCta = {
  __typename?: 'EventsEventsCta';
  label?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  whatsappMessage?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type EventsEvents = {
  __typename?: 'EventsEvents';
  id: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date: Scalars['String']['output'];
  time?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<EventsEventsCta>;
};

export type Events = Node & Document & {
  __typename?: 'Events';
  events?: Maybe<Array<Maybe<EventsEvents>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type EventsEventsCtaFilter = {
  label?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  whatsappMessage?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type EventsEventsFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  cta?: InputMaybe<EventsEventsCtaFilter>;
};

export type EventsFilter = {
  events?: InputMaybe<EventsEventsFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSettings: Settings;
  createSettings: Settings;
  updatePages: Pages;
  createPages: Pages;
  updateRestaurants: Restaurants;
  createRestaurants: Restaurants;
  updateLaundry: Laundry;
  createLaundry: Laundry;
  updateTransport: Transport;
  createTransport: Transport;
  updateBars: Bars;
  createBars: Bars;
  updateActivities: Activities;
  createActivities: Activities;
  updateAmenities: Amenities;
  createAmenities: Amenities;
  updateEvents: Events;
  createEvents: Events;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateRestaurantsArgs = {
  relativePath: Scalars['String']['input'];
  params: RestaurantsMutation;
};


export type MutationCreateRestaurantsArgs = {
  relativePath: Scalars['String']['input'];
  params: RestaurantsMutation;
};


export type MutationUpdateLaundryArgs = {
  relativePath: Scalars['String']['input'];
  params: LaundryMutation;
};


export type MutationCreateLaundryArgs = {
  relativePath: Scalars['String']['input'];
  params: LaundryMutation;
};


export type MutationUpdateTransportArgs = {
  relativePath: Scalars['String']['input'];
  params: TransportMutation;
};


export type MutationCreateTransportArgs = {
  relativePath: Scalars['String']['input'];
  params: TransportMutation;
};


export type MutationUpdateBarsArgs = {
  relativePath: Scalars['String']['input'];
  params: BarsMutation;
};


export type MutationCreateBarsArgs = {
  relativePath: Scalars['String']['input'];
  params: BarsMutation;
};


export type MutationUpdateActivitiesArgs = {
  relativePath: Scalars['String']['input'];
  params: ActivitiesMutation;
};


export type MutationCreateActivitiesArgs = {
  relativePath: Scalars['String']['input'];
  params: ActivitiesMutation;
};


export type MutationUpdateAmenitiesArgs = {
  relativePath: Scalars['String']['input'];
  params: AmenitiesMutation;
};


export type MutationCreateAmenitiesArgs = {
  relativePath: Scalars['String']['input'];
  params: AmenitiesMutation;
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};

export type DocumentUpdateMutation = {
  settings?: InputMaybe<SettingsMutation>;
  pages?: InputMaybe<PagesMutation>;
  restaurants?: InputMaybe<RestaurantsMutation>;
  laundry?: InputMaybe<LaundryMutation>;
  transport?: InputMaybe<TransportMutation>;
  bars?: InputMaybe<BarsMutation>;
  activities?: InputMaybe<ActivitiesMutation>;
  amenities?: InputMaybe<AmenitiesMutation>;
  events?: InputMaybe<EventsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  settings?: InputMaybe<SettingsMutation>;
  pages?: InputMaybe<PagesMutation>;
  restaurants?: InputMaybe<RestaurantsMutation>;
  laundry?: InputMaybe<LaundryMutation>;
  transport?: InputMaybe<TransportMutation>;
  bars?: InputMaybe<BarsMutation>;
  activities?: InputMaybe<ActivitiesMutation>;
  amenities?: InputMaybe<AmenitiesMutation>;
  events?: InputMaybe<EventsMutation>;
};

export type SettingsBrandingMutation = {
  primaryColor?: InputMaybe<Scalars['String']['input']>;
  accentColor?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsWifiMutation = {
  networkName?: InputMaybe<Scalars['String']['input']>;
  password?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsCheckTimesMutation = {
  checkIn?: InputMaybe<Scalars['String']['input']>;
  checkOut?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsContactsMutation = {
  whatsapp?: InputMaybe<Scalars['String']['input']>;
  emergencyLocal?: InputMaybe<Scalars['String']['input']>;
  emergencyAmbulance?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  hostelName?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  branding?: InputMaybe<SettingsBrandingMutation>;
  wifi?: InputMaybe<SettingsWifiMutation>;
  checkTimes?: InputMaybe<SettingsCheckTimesMutation>;
  contacts?: InputMaybe<SettingsContactsMutation>;
  timezone?: InputMaybe<Scalars['String']['input']>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type RestaurantsSpotsCoordinatesMutation = {
  lat?: InputMaybe<Scalars['Float']['input']>;
  lng?: InputMaybe<Scalars['Float']['input']>;
};

export type RestaurantsSpotsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  isHotelService?: InputMaybe<Scalars['Boolean']['input']>;
  linkedAmenityId?: InputMaybe<Scalars['String']['input']>;
  cuisineType?: InputMaybe<Scalars['String']['input']>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  coordinates?: InputMaybe<RestaurantsSpotsCoordinatesMutation>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RestaurantsMutation = {
  spots?: InputMaybe<Array<InputMaybe<RestaurantsSpotsMutation>>>;
};

export type LaundrySpotsCoordinatesMutation = {
  lat?: InputMaybe<Scalars['Float']['input']>;
  lng?: InputMaybe<Scalars['Float']['input']>;
};

export type LaundrySpotsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  isHotelService?: InputMaybe<Scalars['Boolean']['input']>;
  linkedAmenityId?: InputMaybe<Scalars['String']['input']>;
  serviceType?: InputMaybe<Scalars['String']['input']>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  coordinates?: InputMaybe<LaundrySpotsCoordinatesMutation>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type LaundryMutation = {
  spots?: InputMaybe<Array<InputMaybe<LaundrySpotsMutation>>>;
};

export type TransportSpotsCoordinatesMutation = {
  lat?: InputMaybe<Scalars['Float']['input']>;
  lng?: InputMaybe<Scalars['Float']['input']>;
};

export type TransportSpotsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  isHotelService?: InputMaybe<Scalars['Boolean']['input']>;
  linkedAmenityId?: InputMaybe<Scalars['String']['input']>;
  transportType?: InputMaybe<Scalars['String']['input']>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  coordinates?: InputMaybe<TransportSpotsCoordinatesMutation>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TransportMutation = {
  spots?: InputMaybe<Array<InputMaybe<TransportSpotsMutation>>>;
};

export type BarsSpotsCoordinatesMutation = {
  lat?: InputMaybe<Scalars['Float']['input']>;
  lng?: InputMaybe<Scalars['Float']['input']>;
};

export type BarsSpotsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  isHotelService?: InputMaybe<Scalars['Boolean']['input']>;
  linkedAmenityId?: InputMaybe<Scalars['String']['input']>;
  barType?: InputMaybe<Scalars['String']['input']>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  coordinates?: InputMaybe<BarsSpotsCoordinatesMutation>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BarsMutation = {
  spots?: InputMaybe<Array<InputMaybe<BarsSpotsMutation>>>;
};

export type ActivitiesSpotsCoordinatesMutation = {
  lat?: InputMaybe<Scalars['Float']['input']>;
  lng?: InputMaybe<Scalars['Float']['input']>;
};

export type ActivitiesSpotsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  isHotelService?: InputMaybe<Scalars['Boolean']['input']>;
  linkedAmenityId?: InputMaybe<Scalars['String']['input']>;
  activityType?: InputMaybe<Scalars['String']['input']>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  coordinates?: InputMaybe<ActivitiesSpotsCoordinatesMutation>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ActivitiesMutation = {
  spots?: InputMaybe<Array<InputMaybe<ActivitiesSpotsMutation>>>;
};

export type AmenitiesAmenitiesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  amenityType?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['JSON']['input']>;
  isHighlighted?: InputMaybe<Scalars['Boolean']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AmenitiesMutation = {
  amenities?: InputMaybe<Array<InputMaybe<AmenitiesAmenitiesMutation>>>;
};

export type EventsEventsCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  whatsappMessage?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type EventsEventsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<EventsEventsCtaMutation>;
};

export type EventsMutation = {
  events?: InputMaybe<Array<InputMaybe<EventsEventsMutation>>>;
};

export type SettingsPartsFragment = { __typename: 'Settings', hostelName: string, logo?: string | null, timezone?: string | null, branding?: { __typename: 'SettingsBranding', primaryColor?: string | null, accentColor?: string | null } | null, wifi?: { __typename: 'SettingsWifi', networkName: string, password: string } | null, checkTimes?: { __typename: 'SettingsCheckTimes', checkIn?: string | null, checkOut?: string | null } | null, contacts?: { __typename: 'SettingsContacts', whatsapp?: string | null, emergencyLocal?: string | null, emergencyAmbulance?: string | null } | null };

export type PagesPartsFragment = { __typename: 'Pages', title: string, body?: any | null };

export type RestaurantsPartsFragment = { __typename: 'Restaurants', spots?: Array<{ __typename: 'RestaurantsSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, cuisineType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'RestaurantsSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null };

export type LaundryPartsFragment = { __typename: 'Laundry', spots?: Array<{ __typename: 'LaundrySpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, serviceType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'LaundrySpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null };

export type TransportPartsFragment = { __typename: 'Transport', spots?: Array<{ __typename: 'TransportSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, transportType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'TransportSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null };

export type BarsPartsFragment = { __typename: 'Bars', spots?: Array<{ __typename: 'BarsSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, barType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'BarsSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null };

export type ActivitiesPartsFragment = { __typename: 'Activities', spots?: Array<{ __typename: 'ActivitiesSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, activityType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'ActivitiesSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null };

export type AmenitiesPartsFragment = { __typename: 'Amenities', amenities?: Array<{ __typename: 'AmenitiesAmenities', id: string, name: string, description?: string | null, amenityType?: string | null, hours?: string | null, price?: string | null, location?: string | null, image?: string | null, details?: any | null, isHighlighted?: boolean | null, tags?: Array<string | null> | null } | null> | null };

export type EventsPartsFragment = { __typename: 'Events', events?: Array<{ __typename: 'EventsEvents', id: string, title: string, description?: string | null, date: string, time?: string | null, location?: string | null, price?: string | null, image?: string | null, cta?: { __typename: 'EventsEventsCta', label?: string | null, type?: string | null, whatsappMessage?: string | null, url?: string | null } | null } | null> | null };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, hostelName: string, logo?: string | null, timezone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, branding?: { __typename: 'SettingsBranding', primaryColor?: string | null, accentColor?: string | null } | null, wifi?: { __typename: 'SettingsWifi', networkName: string, password: string } | null, checkTimes?: { __typename: 'SettingsCheckTimes', checkIn?: string | null, checkOut?: string | null } | null, contacts?: { __typename: 'SettingsContacts', whatsapp?: string | null, emergencyLocal?: string | null, emergencyAmbulance?: string | null } | null } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, hostelName: string, logo?: string | null, timezone?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, branding?: { __typename: 'SettingsBranding', primaryColor?: string | null, accentColor?: string | null } | null, wifi?: { __typename: 'SettingsWifi', networkName: string, password: string } | null, checkTimes?: { __typename: 'SettingsCheckTimes', checkIn?: string | null, checkOut?: string | null } | null, contacts?: { __typename: 'SettingsContacts', whatsapp?: string | null, emergencyLocal?: string | null, emergencyAmbulance?: string | null } | null } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type RestaurantsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RestaurantsQuery = { __typename?: 'Query', restaurants: { __typename: 'Restaurants', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'RestaurantsSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, cuisineType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'RestaurantsSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } };

export type RestaurantsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RestaurantsFilter>;
}>;


export type RestaurantsConnectionQuery = { __typename?: 'Query', restaurantsConnection: { __typename?: 'RestaurantsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RestaurantsConnectionEdges', cursor: string, node?: { __typename: 'Restaurants', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'RestaurantsSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, cuisineType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'RestaurantsSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } | null } | null> | null } };

export type LaundryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LaundryQuery = { __typename?: 'Query', laundry: { __typename: 'Laundry', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'LaundrySpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, serviceType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'LaundrySpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } };

export type LaundryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LaundryFilter>;
}>;


export type LaundryConnectionQuery = { __typename?: 'Query', laundryConnection: { __typename?: 'LaundryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LaundryConnectionEdges', cursor: string, node?: { __typename: 'Laundry', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'LaundrySpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, serviceType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'LaundrySpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } | null } | null> | null } };

export type TransportQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TransportQuery = { __typename?: 'Query', transport: { __typename: 'Transport', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'TransportSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, transportType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'TransportSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } };

export type TransportConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TransportFilter>;
}>;


export type TransportConnectionQuery = { __typename?: 'Query', transportConnection: { __typename?: 'TransportConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TransportConnectionEdges', cursor: string, node?: { __typename: 'Transport', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'TransportSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, transportType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'TransportSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } | null } | null> | null } };

export type BarsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BarsQuery = { __typename?: 'Query', bars: { __typename: 'Bars', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'BarsSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, barType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'BarsSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } };

export type BarsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BarsFilter>;
}>;


export type BarsConnectionQuery = { __typename?: 'Query', barsConnection: { __typename?: 'BarsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BarsConnectionEdges', cursor: string, node?: { __typename: 'Bars', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'BarsSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, barType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'BarsSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } | null } | null> | null } };

export type ActivitiesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ActivitiesQuery = { __typename?: 'Query', activities: { __typename: 'Activities', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'ActivitiesSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, activityType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'ActivitiesSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } };

export type ActivitiesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActivitiesFilter>;
}>;


export type ActivitiesConnectionQuery = { __typename?: 'Query', activitiesConnection: { __typename?: 'ActivitiesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ActivitiesConnectionEdges', cursor: string, node?: { __typename: 'Activities', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, spots?: Array<{ __typename: 'ActivitiesSpots', id: string, name: string, description?: string | null, isHotelService?: boolean | null, linkedAmenityId?: string | null, activityType?: string | null, priceRange?: string | null, image?: string | null, address?: string | null, tags?: Array<string | null> | null, coordinates?: { __typename: 'ActivitiesSpotsCoordinates', lat?: number | null, lng?: number | null } | null } | null> | null } | null } | null> | null } };

export type AmenitiesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AmenitiesQuery = { __typename?: 'Query', amenities: { __typename: 'Amenities', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, amenities?: Array<{ __typename: 'AmenitiesAmenities', id: string, name: string, description?: string | null, amenityType?: string | null, hours?: string | null, price?: string | null, location?: string | null, image?: string | null, details?: any | null, isHighlighted?: boolean | null, tags?: Array<string | null> | null } | null> | null } };

export type AmenitiesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AmenitiesFilter>;
}>;


export type AmenitiesConnectionQuery = { __typename?: 'Query', amenitiesConnection: { __typename?: 'AmenitiesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AmenitiesConnectionEdges', cursor: string, node?: { __typename: 'Amenities', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, amenities?: Array<{ __typename: 'AmenitiesAmenities', id: string, name: string, description?: string | null, amenityType?: string | null, hours?: string | null, price?: string | null, location?: string | null, image?: string | null, details?: any | null, isHighlighted?: boolean | null, tags?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type EventsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventsQuery = { __typename?: 'Query', events: { __typename: 'Events', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, events?: Array<{ __typename: 'EventsEvents', id: string, title: string, description?: string | null, date: string, time?: string | null, location?: string | null, price?: string | null, image?: string | null, cta?: { __typename: 'EventsEventsCta', label?: string | null, type?: string | null, whatsappMessage?: string | null, url?: string | null } | null } | null> | null } };

export type EventsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
}>;


export type EventsConnectionQuery = { __typename?: 'Query', eventsConnection: { __typename?: 'EventsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventsConnectionEdges', cursor: string, node?: { __typename: 'Events', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, events?: Array<{ __typename: 'EventsEvents', id: string, title: string, description?: string | null, date: string, time?: string | null, location?: string | null, price?: string | null, image?: string | null, cta?: { __typename: 'EventsEventsCta', label?: string | null, type?: string | null, whatsappMessage?: string | null, url?: string | null } | null } | null> | null } | null } | null> | null } };

export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  hostelName
  logo
  branding {
    __typename
    primaryColor
    accentColor
  }
  wifi {
    __typename
    networkName
    password
  }
  checkTimes {
    __typename
    checkIn
    checkOut
  }
  contacts {
    __typename
    whatsapp
    emergencyLocal
    emergencyAmbulance
  }
  timezone
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  body
}
    `;
export const RestaurantsPartsFragmentDoc = gql`
    fragment RestaurantsParts on Restaurants {
  __typename
  spots {
    __typename
    id
    name
    description
    isHotelService
    linkedAmenityId
    cuisineType
    priceRange
    image
    address
    coordinates {
      __typename
      lat
      lng
    }
    tags
  }
}
    `;
export const LaundryPartsFragmentDoc = gql`
    fragment LaundryParts on Laundry {
  __typename
  spots {
    __typename
    id
    name
    description
    isHotelService
    linkedAmenityId
    serviceType
    priceRange
    image
    address
    coordinates {
      __typename
      lat
      lng
    }
    tags
  }
}
    `;
export const TransportPartsFragmentDoc = gql`
    fragment TransportParts on Transport {
  __typename
  spots {
    __typename
    id
    name
    description
    isHotelService
    linkedAmenityId
    transportType
    priceRange
    image
    address
    coordinates {
      __typename
      lat
      lng
    }
    tags
  }
}
    `;
export const BarsPartsFragmentDoc = gql`
    fragment BarsParts on Bars {
  __typename
  spots {
    __typename
    id
    name
    description
    isHotelService
    linkedAmenityId
    barType
    priceRange
    image
    address
    coordinates {
      __typename
      lat
      lng
    }
    tags
  }
}
    `;
export const ActivitiesPartsFragmentDoc = gql`
    fragment ActivitiesParts on Activities {
  __typename
  spots {
    __typename
    id
    name
    description
    isHotelService
    linkedAmenityId
    activityType
    priceRange
    image
    address
    coordinates {
      __typename
      lat
      lng
    }
    tags
  }
}
    `;
export const AmenitiesPartsFragmentDoc = gql`
    fragment AmenitiesParts on Amenities {
  __typename
  amenities {
    __typename
    id
    name
    description
    amenityType
    hours
    price
    location
    image
    details
    isHighlighted
    tags
  }
}
    `;
export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  events {
    __typename
    id
    title
    description
    date
    time
    location
    price
    image
    cta {
      __typename
      label
      type
      whatsappMessage
      url
    }
  }
}
    `;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const RestaurantsDocument = gql`
    query restaurants($relativePath: String!) {
  restaurants(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RestaurantsParts
  }
}
    ${RestaurantsPartsFragmentDoc}`;
export const RestaurantsConnectionDocument = gql`
    query restaurantsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RestaurantsFilter) {
  restaurantsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RestaurantsParts
      }
    }
  }
}
    ${RestaurantsPartsFragmentDoc}`;
export const LaundryDocument = gql`
    query laundry($relativePath: String!) {
  laundry(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LaundryParts
  }
}
    ${LaundryPartsFragmentDoc}`;
export const LaundryConnectionDocument = gql`
    query laundryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LaundryFilter) {
  laundryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LaundryParts
      }
    }
  }
}
    ${LaundryPartsFragmentDoc}`;
export const TransportDocument = gql`
    query transport($relativePath: String!) {
  transport(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TransportParts
  }
}
    ${TransportPartsFragmentDoc}`;
export const TransportConnectionDocument = gql`
    query transportConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TransportFilter) {
  transportConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TransportParts
      }
    }
  }
}
    ${TransportPartsFragmentDoc}`;
export const BarsDocument = gql`
    query bars($relativePath: String!) {
  bars(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BarsParts
  }
}
    ${BarsPartsFragmentDoc}`;
export const BarsConnectionDocument = gql`
    query barsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BarsFilter) {
  barsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BarsParts
      }
    }
  }
}
    ${BarsPartsFragmentDoc}`;
export const ActivitiesDocument = gql`
    query activities($relativePath: String!) {
  activities(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ActivitiesParts
  }
}
    ${ActivitiesPartsFragmentDoc}`;
export const ActivitiesConnectionDocument = gql`
    query activitiesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ActivitiesFilter) {
  activitiesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ActivitiesParts
      }
    }
  }
}
    ${ActivitiesPartsFragmentDoc}`;
export const AmenitiesDocument = gql`
    query amenities($relativePath: String!) {
  amenities(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AmenitiesParts
  }
}
    ${AmenitiesPartsFragmentDoc}`;
export const AmenitiesConnectionDocument = gql`
    query amenitiesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AmenitiesFilter) {
  amenitiesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AmenitiesParts
      }
    }
  }
}
    ${AmenitiesPartsFragmentDoc}`;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    restaurants(variables: RestaurantsQueryVariables, options?: C): Promise<{data: RestaurantsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantsQueryVariables, query: string}> {
        return requester<{data: RestaurantsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantsQueryVariables, query: string}, RestaurantsQueryVariables>(RestaurantsDocument, variables, options);
      },
    restaurantsConnection(variables?: RestaurantsConnectionQueryVariables, options?: C): Promise<{data: RestaurantsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantsConnectionQueryVariables, query: string}> {
        return requester<{data: RestaurantsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RestaurantsConnectionQueryVariables, query: string}, RestaurantsConnectionQueryVariables>(RestaurantsConnectionDocument, variables, options);
      },
    laundry(variables: LaundryQueryVariables, options?: C): Promise<{data: LaundryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LaundryQueryVariables, query: string}> {
        return requester<{data: LaundryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LaundryQueryVariables, query: string}, LaundryQueryVariables>(LaundryDocument, variables, options);
      },
    laundryConnection(variables?: LaundryConnectionQueryVariables, options?: C): Promise<{data: LaundryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LaundryConnectionQueryVariables, query: string}> {
        return requester<{data: LaundryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LaundryConnectionQueryVariables, query: string}, LaundryConnectionQueryVariables>(LaundryConnectionDocument, variables, options);
      },
    transport(variables: TransportQueryVariables, options?: C): Promise<{data: TransportQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TransportQueryVariables, query: string}> {
        return requester<{data: TransportQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TransportQueryVariables, query: string}, TransportQueryVariables>(TransportDocument, variables, options);
      },
    transportConnection(variables?: TransportConnectionQueryVariables, options?: C): Promise<{data: TransportConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TransportConnectionQueryVariables, query: string}> {
        return requester<{data: TransportConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TransportConnectionQueryVariables, query: string}, TransportConnectionQueryVariables>(TransportConnectionDocument, variables, options);
      },
    bars(variables: BarsQueryVariables, options?: C): Promise<{data: BarsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BarsQueryVariables, query: string}> {
        return requester<{data: BarsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BarsQueryVariables, query: string}, BarsQueryVariables>(BarsDocument, variables, options);
      },
    barsConnection(variables?: BarsConnectionQueryVariables, options?: C): Promise<{data: BarsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BarsConnectionQueryVariables, query: string}> {
        return requester<{data: BarsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BarsConnectionQueryVariables, query: string}, BarsConnectionQueryVariables>(BarsConnectionDocument, variables, options);
      },
    activities(variables: ActivitiesQueryVariables, options?: C): Promise<{data: ActivitiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesQueryVariables, query: string}> {
        return requester<{data: ActivitiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesQueryVariables, query: string}, ActivitiesQueryVariables>(ActivitiesDocument, variables, options);
      },
    activitiesConnection(variables?: ActivitiesConnectionQueryVariables, options?: C): Promise<{data: ActivitiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesConnectionQueryVariables, query: string}> {
        return requester<{data: ActivitiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActivitiesConnectionQueryVariables, query: string}, ActivitiesConnectionQueryVariables>(ActivitiesConnectionDocument, variables, options);
      },
    amenities(variables: AmenitiesQueryVariables, options?: C): Promise<{data: AmenitiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AmenitiesQueryVariables, query: string}> {
        return requester<{data: AmenitiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AmenitiesQueryVariables, query: string}, AmenitiesQueryVariables>(AmenitiesDocument, variables, options);
      },
    amenitiesConnection(variables?: AmenitiesConnectionQueryVariables, options?: C): Promise<{data: AmenitiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AmenitiesConnectionQueryVariables, query: string}> {
        return requester<{data: AmenitiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AmenitiesConnectionQueryVariables, query: string}, AmenitiesConnectionQueryVariables>(AmenitiesConnectionDocument, variables, options);
      },
    events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  